FROM mcr.microsoft.com/devcontainers/miniconda:0-3

ARG NODE_VERSION="lts/*"
RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi
RUN mkdir env

WORKDIR /env/
RUN ls -latrh
COPY conda_env.yml .

RUN conda env create -f conda_env.yml
SHELL ["conda", "run", "-n", "arena", "/bin/bash", "-c"]

# [Optional] Uncomment to install a different version of Python than the default
# RUN conda install -y python=3.6 \
#     && pip install --no-cache-dir pipx \
#     && pipx reinstall-all

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>